### ISSUE TITLE
Add support to deprecate endpoints 

### ISSUE THREAD

**Issue by nikhilaroratgo** [taymyr/lagom-samples#14]
@Operation supports the field `deprecated = true`. Adding this field doesn't generate the yml with deprecated field.
For example
 ```
@Operation(
        deprecated = true,
        operationId = "testOperationId",
        description = "This is a test description",
        summary = "(DEPRECATED)",
        parameters = { ..
      )
```

It would be nice to have this feature
Meanwhile, I used `summary` field for this purpose

**Comment by ihostage** [comment]
Duplicate of https://github.com/taymyr/lagom-openapi/issues/40
